version: '3.8'
services:
  learning:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '15432:5432'
    volumes: 
      - learning:/var/lib/postgresql/data
volumes:
  learning:
    driver: local